name = "Examples"

[deps]
FMI = "14a09403-18e3-468f-ad8a-74f8dda2d9ac"
FMIZoo = "724179cf-c260-40a9-bd27-cccc6fe2f195"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6"
