name = "Examples"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
FMI = "14a09403-18e3-468f-ad8a-74f8dda2d9ac"
FMICore = "8af89139-c281-408e-bce2-3005eb87462f"
FMIZoo = "724179cf-c260-40a9-bd27-cccc6fe2f195"
Folds = "41a02a25-b8f0-4f67-bc48-60067656b558"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1.6"
