name: Run PkgEval

on: 
  workflow_dispatch:
  pull_request:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # Don't cancel in-progress jobs if any matrix job fails
      fail-fast: false
      matrix:
        julia-version: ['1'] # "1" automatically expands to the latest stable 1.x release of Julia
        julia-arch: [x64]
    
    steps:
      # Required by PkgEval.jl as xvfb runs into issues with ubuntu 24. See ci.yml workflow of PkgEval.jl repo
      - name: "Allow unprivileged user namespaces"
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v4

      # Set up Julia
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
        id: version

      # Set up julia-cache
      - name: Set up julia-cache
        uses: julia-actions/cache@v2

      # Set up cache
      - name: "Set up cache"
        uses: actions/cache@v4
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-

      # Build package
      - name: "Build package"
        uses: julia-actions/julia-buildpkg@v1

      # Run PkgEval
      - name: "Run PkgEval"
        run: |
          git clone https://github.com/JuliaCI/PkgEval.jl.git
          julia --project=. -e '
            import Pkg;
            Pkg.instantiate();
            Pkg.add("Test");
            Pkg.add(path="./PkgEval.jl")'
          julia --project=. ./test/eval.jl
